[package]
name = "mpdelta_rendering_controller"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
mpdelta_core = { workspace = true }
mpdelta_renderer = { workspace = true }
