[package]
name = "mpdelta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    ".",
    "mpdelta_build_utils/rust_gpu_builder",
    "mpdelta_build_utils/shader_builder",
    "mpdelta_components",
    "mpdelta_core",
    "mpdelta_core_vulkano",
    "mpdelta_gui",
    "mpdelta_gui_vulkano",
    "mpdelta_services",
    "mpdelta_renderer",
    "mpdelta_video_renderer_vulkano",
    "mpdelta_video_renderer_vulkano/shaders/composite_operation_shader",
    "mpdelta_video_renderer_vulkano/shaders/texture_drawing_shader",
]
default-members = [
    ".",
    "mpdelta_build_utils/shader_builder",
    "mpdelta_components",
    "mpdelta_core",
    "mpdelta_core_vulkano",
    "mpdelta_gui",
    "mpdelta_gui_vulkano",
    "mpdelta_services",
    "mpdelta_renderer",
    "mpdelta_video_renderer_vulkano",
]

[dependencies]
vulkano = "0.30.0"
vulkano-win = "0.30.0"
winit = "0.26.0"
mpdelta_components = { path = "mpdelta_components" }
mpdelta_core = { path = "mpdelta_core" }
mpdelta_core_vulkano = { path = "mpdelta_core_vulkano" }
mpdelta_services = { path = "mpdelta_services" }
mpdelta_renderer = { path = "mpdelta_renderer" }
mpdelta_video_renderer_vulkano = { path = "mpdelta_video_renderer_vulkano" }
mpdelta_gui = { path = "mpdelta_gui" }
mpdelta_gui_vulkano = { path = "mpdelta_gui_vulkano" }
tokio = { version = "1.19.2", features = ["full"] }
async-trait = "0.1.56"

[profile.dev]
opt-level = 1
incremental = false

[profile.release]
incremental = false
