[package]
name = "mpdelta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "mpdelta_core",
    "mpdelta_gui",
    "mpdelta_gui_vulkano",
    "mpdelta_services",
]

[dependencies]
vulkano = "0.29.0"
vulkano-win = "0.29.0"
winit = "0.26.0"
mpdelta_core = { path = "mpdelta_core" }
mpdelta_gui = { path = "mpdelta_gui" }
mpdelta_gui_vulkano = { path = "mpdelta_gui_vulkano" }
