[package]
name = "mpdelta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["mpdelta_core"]

[dependencies]
mpdelta_core = { path = "mpdelta_core" }
