[package]
name = "mpdelta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    ".",
    "mpdelta_build_utils/rust_gpu_builder",
    "mpdelta_build_utils/shader_builder",
    "mpdelta_components",
    "mpdelta_core",
    "mpdelta_core_vulkano",
    "mpdelta_gui",
    "mpdelta_gui_vulkano",
    "mpdelta_services",
    "mpdelta_renderer",
    "mpdelta_video_renderer_vulkano",
    "mpdelta_video_renderer_vulkano/shaders/composite_operation",
    "mpdelta_video_renderer_vulkano/shaders/texture_drawing",
]
default-members = [
    ".",
    "mpdelta_build_utils/shader_builder",
    "mpdelta_components",
    "mpdelta_core",
    "mpdelta_core_vulkano",
    "mpdelta_gui",
    "mpdelta_gui_vulkano",
    "mpdelta_services",
    "mpdelta_renderer",
    "mpdelta_video_renderer_vulkano",
]

[workspace.dependencies]
arc-swap = "1.5.1"
arrayvec = "0.7.2"
async-trait = "0.1.56"
bitflags = "1.3.2"
bytemuck = "1.12.3"
bytemuck_derive = "1.3.0"
cgmath = "0.18.0"
clap = { version = "3.2.16", features = ["derive"] }
dashmap = "5.3.4"
egui = "0.21.0"
egui_winit_vulkano = "0.24.0"
either = "1.7.0"
futures = "0.3.21"
glam = { version = "0.22", default-features = false, features = ["libm"] }
mpdelta_components = { path = "mpdelta_components" }
mpdelta_core = { path = "mpdelta_core" }
mpdelta_core_vulkano = { path = "mpdelta_core_vulkano" }
mpdelta_gui = { path = "mpdelta_gui" }
mpdelta_gui_vulkano = { path = "mpdelta_gui_vulkano" }
mpdelta_renderer = { path = "mpdelta_renderer" }
mpdelta_services = { path = "mpdelta_services" }
mpdelta_video_renderer_vulkano = { path = "mpdelta_video_renderer_vulkano" }
once_cell = "1.13.1"
qcell = "0.5.2"
regex = "1.6.0"
shader_builder = { path = "mpdelta_build_utils/shader_builder" }
spirv-builder = "0.7.0"
spirv-std = "0.7.0"
thiserror = "1.0.31"
time = { version = "0.3.11", features = ["std"] }
tokio = { version = "1.19.2", features = ["full"] }
uuid = "1.0.0"
vulkano = "0.33.0"
vulkano-util = "0.33.0"
vulkano-win = "0.33.0"
winit = "0.28.3"


[dependencies]
async-trait = { workspace = true }
mpdelta_components = { workspace = true }
mpdelta_core = { workspace = true }
mpdelta_core_vulkano = { workspace = true }
mpdelta_gui = { workspace = true }
mpdelta_gui_vulkano = { workspace = true }
mpdelta_renderer = { workspace = true }
mpdelta_services = { workspace = true }
mpdelta_video_renderer_vulkano = { workspace = true }
qcell = { workspace = true }
tokio = { workspace = true }
vulkano = { workspace = true }
vulkano-util = { workspace = true }
vulkano-win = { workspace = true }
winit = { workspace = true }

[profile.dev]
opt-level = 1
incremental = false

[profile.release]
incremental = false
