[package]
name = "mpdelta"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
default-run = "mpdelta"

[workspace]
members = [
    ".",
    "mpdelta_audio_mixer",
    "mpdelta_build_utils/rust_gpu_builder",
    "mpdelta_build_utils/shader_builder",
    "mpdelta_common/mpdelta_async_runtime",
    "mpdelta_common/mpdelta_dsp",
    "mpdelta_common/mpdelta_ffmpeg",
    "mpdelta_components",
    "mpdelta_core",
    "mpdelta_core_audio",
    "mpdelta_core_vulkano",
    "mpdelta_differential",
    "mpdelta_dyn_usecase",
    "mpdelta_gui",
    "mpdelta_gui_audio_player_cpal",
    "mpdelta_gui_hot_reload",
    "mpdelta_gui_hot_reload/mpdelta_gui_hot_reload_lib",
    "mpdelta_gui_vulkano",
    "mpdelta_multimedia",
    "mpdelta_multimedia_encoder_ffmpeg",
    "mpdelta_renderer",
    "mpdelta_rendering_controller",
    "mpdelta_services",
    "mpdelta_video_renderer_vulkano",
    "mpdelta_video_renderer_vulkano/shaders/composite_operation",
    "mpdelta_video_renderer_vulkano/shaders/texture_drawing",
]
default-members = [
    ".",
    "mpdelta_audio_mixer",
    "mpdelta_build_utils/shader_builder",
    "mpdelta_common/mpdelta_async_runtime",
    "mpdelta_common/mpdelta_dsp",
    "mpdelta_common/mpdelta_ffmpeg",
    "mpdelta_components",
    "mpdelta_core",
    "mpdelta_core_audio",
    "mpdelta_core_vulkano",
    "mpdelta_differential",
    "mpdelta_dyn_usecase",
    "mpdelta_gui",
    "mpdelta_gui_audio_player_cpal",
    "mpdelta_gui_hot_reload",
    "mpdelta_gui_hot_reload/mpdelta_gui_hot_reload_lib",
    "mpdelta_gui_vulkano",
    "mpdelta_multimedia",
    "mpdelta_multimedia_encoder_ffmpeg",
    "mpdelta_services",
    "mpdelta_renderer",
    "mpdelta_rendering_controller",
    "mpdelta_video_renderer_vulkano",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["White-Green"]

[workspace.dependencies]
arc-swap = "1.6.0"
assert_matches = "1.5.0"
async-trait = "0.1.77"
bytemuck = "1.14.0"
bytemuck_derive = "1.5.0"
cgmath = "0.18.0"
clap = { version = "4.4.12", features = ["derive"] }
cpal = "0.15.2"
crossbeam-queue = "0.3.10"
dashmap = "5.5.3"
egui = "0.24.1"
egui_image_renderer = { git = "https://github.com/White-Green/egui_image_renderer", rev = "9e4a24b689029863f39c48a53a4aba3bae948ecd" }
egui_winit_vulkano = "0.27.0"
either = "1.9.0"
ffmpeg-next = { version = "6.1.1", default-features = false, features = ["codec", "format", "software-scaling", "software-resampling"] }
ffmpeg-sys-next = { version = "6.1.0", default-features = false, features = ["avcodec", "avdevice", "avfilter", "avformat", "swresample", "swscale"] }
futures = "0.3.30"
glam = { version = "0.24", default-features = false, features = ["libm"] }
hot-lib-reloader = "0.6.5"
indexmap = "2.1.0"
lru = "0.12.1"
mpdelta_async_runtime = { path = "mpdelta_common/mpdelta_async_runtime" }
mpdelta_audio_mixer = { path = "mpdelta_audio_mixer" }
mpdelta_components = { path = "mpdelta_components" }
mpdelta_core = { path = "mpdelta_core" }
mpdelta_core_audio = { path = "mpdelta_core_audio" }
mpdelta_core_vulkano = { path = "mpdelta_core_vulkano" }
mpdelta_differential = { path = "mpdelta_differential" }
mpdelta_dsp = { path = "mpdelta_common/mpdelta_dsp" }
mpdelta_dyn_usecase = { path = "mpdelta_dyn_usecase" }
mpdelta_ffmpeg = { path = "mpdelta_common/mpdelta_ffmpeg" }
mpdelta_gui = { path = "mpdelta_gui" }
mpdelta_gui_audio_player_cpal = { path = "mpdelta_gui_audio_player_cpal" }
mpdelta_gui_vulkano = { path = "mpdelta_gui_vulkano" }
mpdelta_multimedia = { path = "mpdelta_multimedia" }
mpdelta_multimedia_encoder_ffmpeg = { path = "mpdelta_multimedia_encoder_ffmpeg" }
mpdelta_renderer = { path = "mpdelta_renderer" }
mpdelta_rendering_controller = { path = "mpdelta_rendering_controller" }
mpdelta_services = { path = "mpdelta_services" }
mpdelta_video_renderer_vulkano = { path = "mpdelta_video_renderer_vulkano" }
notify = "6.1.1"
num = "0.4.1"
once_cell = "1.19.0"
proptest = "1.4.0"
qcell = "0.5.4"
rayon = "1.8.0"
regex = "1.10.2"
rfd = { version = "0.13.0", features = ["file-handle-inner"] }
shader_builder = { path = "mpdelta_build_utils/shader_builder" }
smallvec = "1.8"
spirv-builder = "0.9.0"
spirv-std = "0.9.0"
thiserror = "1.0.56"
time = { version = "0.3.31", features = ["std"] }
tokio = { version = "1.35.1", features = ["fs", "macros", "sync", "time"] }
uuid = "1.6.1"
vulkano = "0.34.1"
vulkano-util = "0.34.1"
vulkano-win = "0.34.0"
winit = "0.28.7"

[dependencies]
async-trait = { workspace = true }
cpal = { workspace = true }
mpdelta_async_runtime = { workspace = true, features = ["tokio"] }
mpdelta_audio_mixer = { workspace = true }
mpdelta_components = { workspace = true }
mpdelta_core = { workspace = true }
mpdelta_core_audio = { workspace = true }
mpdelta_core_vulkano = { workspace = true }
mpdelta_gui = { workspace = true }
mpdelta_gui_audio_player_cpal = { workspace = true }
mpdelta_gui_vulkano = { workspace = true }
mpdelta_multimedia = { workspace = true }
mpdelta_multimedia_encoder_ffmpeg = { workspace = true }
mpdelta_renderer = { workspace = true }
mpdelta_rendering_controller = { workspace = true }
mpdelta_services = { workspace = true }
mpdelta_video_renderer_vulkano = { workspace = true }
qcell = { workspace = true }
tokio = { workspace = true }
vulkano = { workspace = true }
vulkano-util = { workspace = true }
vulkano-win = { workspace = true }
winit = { workspace = true }

[profile.dev]
opt-level = 1
incremental = false

[profile.release]
incremental = false
