[package]
authors = { workspace = true }
edition = { workspace = true }
name = "shader_texture_drawing"
version = { workspace = true }

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
bytemuck = { workspace = true }
spirv-std = { optional = true, workspace = true }

[features]
default = ["shader"]
shader = ["spirv-std"]

[lints.rust]
unexpected_cfgs = { check-cfg = [
  'cfg(target_arch, values("spirv"))',
], level = "deny" }
