[package]
authors = { workspace = true }
edition = { workspace = true }
name = "mpdelta_services"
version = { workspace = true }

[dependencies]
async-trait = { workspace = true }
cgmath = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
mpdelta_core = { workspace = true }
mpdelta_differential = { workspace = true }
rpds = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
uuid = { features = ["rng", "v1"], workspace = true }

[dev-dependencies]
mpdelta_core_test_util = { workspace = true }
tokio = { features = ["rt-multi-thread"], workspace = true }
