[package]
authors = { workspace = true }
edition = { workspace = true }
name = "mpdelta_project_serialize"
version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
cgmath = { workspace = true }
ciborium = { workspace = true }
erased-serde = { workspace = true }
futures = { features = ["alloc"], workspace = true }
mpdelta_core = { workspace = true }
mpdelta_differential = { workspace = true }
rayon = { workspace = true }
rpds = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { features = ["rt"], workspace = true }
uuid = { features = ["serde"], workspace = true }

[dev-dependencies]
mpdelta_core = { features = ["proptest"], workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
