[package]
authors = { workspace = true }
edition = { workspace = true }
name = "mpdelta_core"
version = { workspace = true }

[dependencies]
arc-swap = { workspace = true }
async-trait = { workspace = true }
cgmath = { workspace = true }
dyn-eq = { workspace = true }
dyn-hash = { workspace = true }
erased-serde = { workspace = true }
futures = { workspace = true }
num = { workspace = true }
proptest = { optional = true, workspace = true }
proptest-derive = { optional = true, workspace = true }
rpds = { workspace = true }
serde = { workspace = true }
serde_repr = { workspace = true }
thiserror = { workspace = true }
tokio = { features = ["sync"], workspace = true }
uuid = { features = ["serde"], workspace = true }

[dev-dependencies]
proptest = { workspace = true }
proptest-derive = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[features]
proptest = ["dep:proptest", "dep:proptest-derive"]
