[package]
name = "mpdelta_gui_vulkano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpdelta_gui = { path = "../mpdelta_gui" }
egui_vulkano = "0.8.0"
vulkano = "0.29.0"
vulkano-win = "0.29.0"
