[package]
authors = { workspace = true }
edition = { workspace = true }
name = "mpdelta_audio_mixer"
version = { workspace = true }

[dependencies]
mpdelta_core = { workspace = true }
mpdelta_core_audio = { workspace = true }
mpdelta_dsp = { workspace = true }
mpdelta_renderer = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
mpdelta_core_test_util = { workspace = true }
mpdelta_dsp = { features = ["formal_test"], workspace = true }
tokio = { features = ["macros", "rt"], workspace = true }
uuid = { workspace = true }
