[package]
name = "mpdelta_differential"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpdelta_core = { workspace = true }
qcell = { workspace = true }
thiserror = { workspace = true }
