[package]
name = "mpdelta_video_renderer_vulkano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
cgmath = { workspace = true }
composite_operation_shader = { path = "shaders/composite_operation_shader" }
dashmap = { workspace = true }
either = { workspace = true }
futures = { workspace = true }
glam = { workspace = true }
mpdelta_core = { workspace = true }
mpdelta_core_vulkano = { workspace = true }
mpdelta_renderer = { workspace = true }
texture_drawing_shader = { path = "shaders/texture_drawing_shader" }
tokio = { workspace = true }
vulkano = { workspace = true }

[build-dependencies]
shader_builder = { workspace = true }
