[package]
name = "mpdelta_video_renderer_vulkano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpdelta_core = { path = "../mpdelta_core" }
mpdelta_renderer = { path = "../mpdelta_renderer" }
