[package]
authors = { workspace = true }
edition = { workspace = true }
name = "mpdelta_video_renderer_vulkano"
version = { workspace = true }


[dependencies]
cgmath = { workspace = true }
futures = { workspace = true }
glam = { workspace = true }
mpdelta_core = { workspace = true }
mpdelta_core_vulkano = { workspace = true }
mpdelta_renderer = { workspace = true }
shader_composite_operation = { default-features = false, path = "shaders/composite_operation", version = "*" }
shader_texture_drawing = { default-features = false, features = [
  "spirv-std",
], path = "shaders/texture_drawing", version = "*" }
smallvec = { workspace = true }
vulkano = { workspace = true }

[build-dependencies]
cargo-gpu-install = { workspace = true }

[dev-dependencies]
tokio = { features = ["macros", "rt"], workspace = true }
vulkano-util = { workspace = true }
