[package]
name = "mpdelta_video_renderer_vulkano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpdelta_core = { path = "../mpdelta_core" }
mpdelta_renderer = { path = "../mpdelta_renderer" }
vulkano = "0.30.0"
async-trait = "0.1.56"

[build-dependencies]
shader_builder = { path = "../mpdelta_build_utils/shader_builder" }
