[package]
name = "mpdelta_component_sine_audio"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
async-trait = { workspace = true }
mpdelta_core = { workspace = true }
mpdelta_core_audio = { workspace = true }
tokio = { workspace = true }
