[package]
name = "mpdelta_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpdelta_core = { path = "../mpdelta_core" }
tokio = { version = "1.19.2", features = ["full"] }
async-trait = "0.1.56"
