[package]
authors = { workspace = true }
edition = { workspace = true }
name = "mpdelta_component_parameters"
version = { workspace = true }

[dependencies]
erased-serde = { workspace = true }
memmap2 = { workspace = true }
mpdelta_core = { workspace = true }
serde = { workspace = true }
uuid = { features = ["v3", "v5"], workspace = true }
