[package]
authors = { workspace = true }
edition = { workspace = true }
name = "mpdelta_ffmpeg"
version = { workspace = true }

[dependencies]
bitflags = { workspace = true }
ffmpeg-next = { workspace = true }
ffmpeg-sys-next = { workspace = true }
mpdelta_multimedia = { workspace = true }
thiserror = { workspace = true }

[package.metadata.vcpkg]
dependencies = ["ffmpeg[avcodec,swresample,swscale,openh264]"]
git = "https://github.com/microsoft/vcpkg"
rev = "6070d5cb2f818921c10ccdf6f35f3415a2503369"
