[package]
authors = { workspace = true }
edition = { workspace = true }
name = "mpdelta_ffmpeg"
version = { workspace = true }

[dependencies]
bitflags = { workspace = true }
ffmpeg-next = { workspace = true }
ffmpeg-sys-next = { workspace = true }
mpdelta_multimedia = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
ffmpeg-sys-next = { features = [
  "build",
  "build-lib-openh264",
  "build-zlib",
], workspace = true }
