[package]
authors = { workspace = true }
edition = { workspace = true }
name = "shader_font_rendering"
version = { workspace = true }

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
bytemuck = { workspace = true }
bytemuck_derive = { workspace = true }
glam = { features = ["bytemuck"], workspace = true }
spirv-std = { optional = true, workspace = true }
vulkano = { optional = true, workspace = true }

[features]
default = ["shader"]
shader = ["dep:spirv-std"]
vulkano = ["dep:vulkano"]

[lints.rust]
unexpected_cfgs = { check-cfg = [
  'cfg(target_arch, values("spirv"))',
], level = "deny" }
