[package]
name = "mpdelta_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpdelta_core = { path = "../mpdelta_core" }
egui = "0.18.1"
tokio = { version = "1.19.2", features = ["full"] }
arc-swap = "1.5.1"
bitflags = "1.3.2"
