[package]
name = "mpdelta_gui"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
[dependencies]
arc-swap = { workspace = true }
bitflags = { workspace = true }
cgmath = { workspace = true }
dashmap = { workspace = true }
egui = { workspace = true }
futures = { workspace = true }
mpdelta_async_runtime = { workspace = true }
mpdelta_core = { workspace = true }
once_cell = { workspace = true }
qcell = { workspace = true }
regex = { workspace = true }
tokio = { workspace = true }
