[package]
name = "mpdelta_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = { workspace = true }
bitflags = { workspace = true }
cgmath = { workspace = true }
dashmap = { workspace = true }
egui = { workspace = true }
mpdelta_core = { workspace = true }
once_cell = { workspace = true }
qcell = { workspace = true }
regex = { workspace = true }
tokio = { workspace = true }
