[package]
name = "mpdelta_dsp"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
num = { workspace = true }
thiserror = { workspace = true }
