name: clippy lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install yasm libgtk-3-dev libasound2-dev libopenh264-dev -y
      - uses: dtolnay/rust-toolchain@stable
        id: main_toolchain
        with:
          components: clippy
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-05-27
          components: "rust-src,rustc-dev,llvm-tools-preview"
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo
      - uses: actions/cache@v4
        with:
          path: |
            target/
            target_for_shaders/
          key: ${{ runner.os }}-cargo-${{ steps.main_toolchain.outputs.name }}-clippy-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: | 
            ${{ runner.os }}-cargo-${{ steps.main_toolchain.outputs.name }}-clippy-
      - run: cargo +stable clippy --workspace --tests --locked -- -D warnings
