name: clippy lint in pull request
on: pull_request

jobs:
  rustfmt:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install yasm libgtk-3-dev libasound2-dev -y
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-05-27
          components: "rust-src,rustc-dev,llvm-tools-preview"
      - run: CARGO_FEATURE_BUILD=1 cargo +stable clippy --workspace -- -D warnings
