name: rustdoc pages
on:
  push

jobs:
  rustdoc:
    permissions:
      contents: read
      pages: write
      id-token: write
    name: rustdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        id: main_toolchain
        with:
          components: clippy
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-05-27
          components: "rust-src,rustc-dev,llvm-tools-preview"
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo
      - uses: actions/cache@v4
        with:
          path: |
            target/
            target_for_shaders/
          key: ${{ runner.os }}-cargo-doc-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo +${{ steps.main_toolchain.outputs.name }} doc --workspace --document-private-items --no-deps -Zrustdoc-map
      - uses: actions/upload-pages-artifact@v2
        with:
          path: target/doc

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: rustdoc
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
